name: 'YAML Lint'
description: 'Validate YAML syntax'
author: 'edshelton'

inputs:
  file_or_dir:
    description: 'File(s) or Directory, separate by space if multiple files or folder are specified'
    required: true
  config_file:
    description: 'Path to custom configuration'
    required: false
  config_data:
    description: 'Custom configuration (as YAML source)'
    required: false
  format:
    description: 'Format for parsing output [parsable,standard,colored,auto]'
    required: false
    default: "auto"
  strict:
    description: 'Return non-zero exit code on warnings as well as errors'
    required: false
    default: "false"
  no_warnings:
    description: 'Disables reporting warnings to STDOUT'
    required: false
    default: "false"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_or_dir }}
    - ${{ inputs.config_file }}
    - ${{ inputs.config_data }}
    - ${{ inputs.format }}
    - ${{ inputs.strict }}
    - ${{ inputs.no_warnings }}

branding:
  color: blue
  icon: check-square
